app_clover_homepage:
    path:     /
    defaults: { _controller: AppCloverBundle:Default:index }

app_clover_tables:
    path:     /tables.html
    defaults: { _controller: AppCloverBundle:Default:tables }

# UI
app_clover_buttons:
    path:     /buttons.html
    defaults: { _controller: AppCloverBundle:UI:buttons }

app_clover_panels:
    path:     /panels.html
    defaults: { _controller: AppCloverBundle:UI:panels }

app_clover_typography:
    path:     /typography.html
    defaults: { _controller: AppCloverBundle:UI:typography }

app_clover_icons:
    path:     /icons.html
    defaults: { _controller: AppCloverBundle:UI:icons }