app_clover_homepage:
    path:     /
    defaults: { _controller: AppCloverBundle:Default:index }

app_clover_tables:
    path:     /tables.html
    defaults: { _controller: AppCloverBundle:Default:tables }

app_clover_typography:
    path:     /typography.html
    defaults: { _controller: AppCloverBundle:UI:typography }